### PR TITLE
RC bump for chisel and firrtl 1.3

### PR DESCRIPTION
**Pull request by colinschmidt**
Updates needed to build with rocket-chip after the chisel and firrtl 1.3 bump

### CODE REVIEW

**Comment by albertchen-sifive** [comment]
sorry. the wit version https://github.com/sifive/block-inclusivecache-sifive/blob/master/continuous-integration/travis/install_deps_linux.sh#L22 should be pinned like on rocket-chip https://github.com/chipsalliance/rocket-chip/pull/2426/files

**Comment by colinschmidt** [comment]
How do I tell it to use the chisel 3.3 version of rocket-chip.
This PR: https://github.com/chipsalliance/rocket-chip/pull/2399

**Comment by colinschmidt** [comment]
Nevermind found it

**Comment by colinschmidt** [comment]
@albertchen-sifive Do you need anything else to get this merged?

**Comment by albertchen-sifive** [comment]
> @albertchen-sifive Do you need anything else to get this merged?

no. sorry just needed a reminder

**Pull request merged**
