### PR TITLE
Update object model for october 2019 rocket-chip

### PR DESCRIPTION
**Pull request by colinschmidt**
I think this would Ideally add all the bank and directory memories but that would be a lot of plumbing, and a lot more code modified.

If the reviewer wants that solution instead please let me know.

### CODE REVIEW

**Comment by colinschmidt** [comment]
Tested with:
 https://github.com/chipsalliance/rocket-chip/commit/4f0cdea85c8a2b849fd582ccc8497892001d06b0

**Comment by colinschmidt** [comment]
@albertchen-sifive Can I get a simple review? I chose you because you have made similar bumps to this repo and sifive-blocks in the past.

**Review by albertchen-sifive — APPROVED** [review]
LGTM. can you also bump the [rocket-chip wit dependency](https://github.com/sifive/block-inclusivecache-sifive/blob/master/wit-manifest.json#L3) to [this commit](https://github.com/chipsalliance/rocket-chip/commit/4f0cdea85c8a2b849fd582ccc8497892001d06b0). I think that's the one with the breaking change.

**Comment by albertchen-sifive** [comment]
wait just kidding. this change still works with old rocket-chip so ignore what I said.

**Comment by colinschmidt** [comment]
FYI, I can't press the merge button.

**Pull request merged**
